### ISSUE TITLE
Input gets overwritten if two users on same geom

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#150]
Hi Ton, Have just been testing with Polly. We've found that if two people select the same geom at the same time and edit then whoever saves last overwrites the data. Ie if i select and polly selected then I add data for a field and save but Polly added data for another field and saved after my edits get removed. The ideal solution is an alert for the user to say the geom is being edited but not sure how the client would know that if they already have the tiles loaded!

**Comment by dominijk** [comment]
To me that solution makes sense as the user will know there's an action for them and a reason for it. I cant think of an easy lock solution with my very basic mapbox knowledge. The mouse click could trigger a message back to the server but that would only get picked up by users loading data after that event even if mouse click also asks server is this tile in edit. Trying to design a lock for simultaneous check out by two users would be very tricky..

**Comment by tomalrussell** [comment]
Suggest we resolve this with a lighter fix: instead of locking the building or making the web client send a message like "change storeys from undefined to 5" and checking that on the server, we could leave it as 'last-write-wins' but ensure that the client only posts the minimal change - i.e. only the fields which the user has actually edited.

This would minimise the surface area for possible clashes, but otherwise keeps the system quite simple.

**Comment by mz8i** [comment]
As far as I understand the problem, this would actually be resolved by #472 which is WIP now - part of the overall changes is only sending the edited fields in an update

**Comment by tomalrussell** [comment]
Core issue closed by #472.
