### ISSUE TITLE
Support user-led data verification

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#199]
## What feature does
Means for user to verify other user input example;

User provides age another user confirms that age

**Comment by polly64** [comment]
- button or tick box as like me- i vote per user per subcategory

**Comment by tomalrussell** [comment]
User flow:
- see 3 :heavy_check_mark: number of verifications
- grey if I haven't verified, green otherwise
- click to verify, increments number, turns green, shows brief thank you message

What happens when someone edits a verified field?
- verifications go to zero
- accumulated verifications should be somehow recorded against previous version ????

**Comment by tomalrussell** [comment]
Notes from #230 
- link verifications to data field and revision
- log verification history as with other edit history
- if a data entry is newly created or changes, set verifications to zero

**Comment by tomalrussell** [comment]
Would be nice to be able to find revisions which contained a given field (for a building) quickly/straightforwardly.

Would be nice to get a notification if someone edited a field that you had also edited.
