### ISSUE TITLE
Style: URL in age

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#515]
@mz8i Is this a styling issue? 

As attached, in view the urls added in age ([example](https://colouring.london/view/age/1154497)) run across the box. In edit mode they are styled differently. Is it possible to disable the hyperlink  and just show the url so there's no click through until #284  is resolved? 

**In view**
<img width="368" alt="Screen Shot 2019-11-22 at 16 39 45" src="https://user-images.githubusercontent.com/6041913/69443730-e93a3800-0d46-11ea-968a-6206c8ddfa0a.png">

**In edit**
<img width="383" alt="Screen Shot 2019-11-22 at 16 42 46" src="https://user-images.githubusercontent.com/6041913/69443872-2a324c80-0d47-11ea-96fe-fdb9093600c4.png">

**Comment by MeldaS** [comment]
This issue seems to have been resolved. Tested the [example](https://colouring.london/view/age/1154497) provided above and the links are styled correctly. 

Edit mode:
<img width="458" alt="Screen Shot 2020-07-07 at 9 54 47 AM" src="https://user-images.githubusercontent.com/33935846/86731224-fe46ab80-c037-11ea-8856-96888e4394a5.png">

View mode:
<img width="454" alt="Screen Shot 2020-07-07 at 9 54 31 AM" src="https://user-images.githubusercontent.com/33935846/86731142-e96a1800-c037-11ea-9feb-6b4201145f73.png">
