### ISSUE TITLE
Cannot log-in

### ISSUE THREAD

**Issue by littleplats** [colouring-london/colouring-london#598]
It wont let me log in. When i insert my user name and PW it says it isnt recognised; when i click on forgotten password, i receive the pw reset link by email, but when i click on it and fill in a new password, it then goes to the login screen again and still doesnt work. It is just sending me round in circles...

**Comment by tomalrussell** [comment]
Thanks for reporting this, sorry it's so frustrating! I'll take a look into what's going on.

**Comment by littleplats** [comment]
Hi

 

Never heard anything more about this and still cannot log in!

 

sam

**Comment by mz8i** [comment]
Hi @littleplats,

Sorry for the lack of progress so far, and hopefully we can resolve the problem so you can start contributing to Colouring London!

I've looked into this and it seems that the password resets you performed went through successfully. Because of this, one possible reason for the failed login could be if you were mistyping your username. Could you please double-check that you are typing the username you registered with? Please note that this is not the email address, and it is case-sensitive.

I have updated the login screen so that it warns when the submitted username doesn't exist in the system. We don't currently have an automated username reminder functionality, but if that turns out to be the case for you, please reply here and I will send the username reminder to the email address you have registered with.

**Comment by littleplats** [comment]
Hi 

 

Thanks for getting back to me. I have no record of what username I originally chose, so please can you let me know what it was? I had been entering my email address as my username so presumably this was indeed the problem.

 

Thanks

sam

**Comment by mz8i** [comment]
Hi @littleplats - I have sent you a reminder to the email address you registered with. 
I will assume this issue is resolved, but feel free to comment here if it turns out there is a different issue.

Hopefully the modification from #617 will help users better determine the specific issue with their log-in details. We'll consider adding log-in with email, or a username reminder functionality for the future.
